# Generated by Django 3.0.2 on 2020-02-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='EducationUser',
            new_name='user',
        ),
    ]
