# Generated by Django 3.0.2 on 2020-02-22 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200220_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='SkillsUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='EmployerUser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
