# Generated by Django 3.0.2 on 2020-02-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200222_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='Employer',
            new_name='EmployerName',
        ),
    ]
