# Generated by Django 3.0.2 on 2020-02-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200225_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='CvEducation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.Education'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='CvSkills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.Skills'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='CvWorkExperience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.WorkExperience'),
        ),
    ]
