# Generated by Django 3.0.2 on 2020-02-25 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200225_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='CvEducation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Education'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='CvSkills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Skills'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='CvWorkExperience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.WorkExperience'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
