# Generated by Django 3.0.2 on 2020-02-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200225_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
    ]
