# Generated by Django 3.0.2 on 2020-03-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200303_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='JobUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
