# Generated by Django 3.0.2 on 2020-03-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='CvFile',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
