# Generated by Django 3.0.2 on 2020-03-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200307_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='CvFile',
        ),
    ]
