# Generated by Django 3.0.2 on 2020-02-06 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default=None, max_length=100, verbose_name='Full Name')),
                ('UserDOB', models.DateField(default=None, verbose_name='DOB')),
                ('UserPhone', models.CharField(default=None, max_length=13, verbose_name='Phone Number')),
                ('UserEmail', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('UserAddress', models.CharField(default=None, max_length=250, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
