# Generated by Django 3.0.2 on 2020-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default=None, max_length=100, verbose_name='Full Name')),
                ('UserDOB', models.DateField(default=None, verbose_name='Age')),
                ('UserPhone', models.CharField(default=None, max_length=13, verbose_name='Phone Number')),
                ('UserEmail', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('UserAddress', models.CharField(default=None, max_length=250, verbose_name='Address')),
            ],
        ),
    ]
