# Generated by Django 3.0.2 on 2020-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployerName', models.CharField(default=None, max_length=100, verbose_name='Institution Name')),
                ('EmployerStartDate', models.DateField(default=None, verbose_name='Employer Start Date')),
                ('EmployerEndDate', models.DateField(default=None, verbose_name='Employer End Date')),
                ('EmployerDesc', models.CharField(default=None, max_length=250, verbose_name='Employer Description')),
            ],
        ),
    ]
